WM('RxW3', function (import, export, default)
    export('Observable', import('RxW3Observable'));
    export('Observer', import('RxW3Observer'));
    export('Subscription', import('RxW3Subscription'));
    export('Util', import('RxW3Util'));
    export('Subjects', import('RxW3Subjects'))
    export('Subjects/Subject', import('RxW3Subjects', 'Subject'));
    export('Subjects/BehaviorSubject', import('RxW3Subjects', 'BehaviorSubject'));
    export('Subjects/ReplaySubject', import('RxW3Subjects', 'ReplaySubject'));
    export('Subjects/AsyncSubject', import('RxW3Subjects', 'AsyncSubject'));
    export('Schedulers', import('RxW3Schedulers'));
    export('Schedulers/TimeoutScheduler', import('RxW3Schedulers', 'TimeoutScheduler'));
    export('Schedulers/ImmediateScheduler', import('RxW3Schedulers', 'ImmediateScheduler'));
    export('Schedulers/CooperativeScheduler', import('RxW3Schedulers', 'CooperativeScheduler'));
    export('Operators', import('RxW3Operators'));
    export('Operators/All', import('RxW3Operators', 'All'));
    export('Operators/Amb', import('RxW3Operators', 'Amb'));
    export('Operators/Average', import('RxW3Operators', 'Average'));
    export('Operators/Buffer', import('RxW3Operators', 'Buffer'));
    export('Operators/Catch', import('RxW3Operators', 'Catch'));
    export('Operators/CombineLatest', import('RxW3Operators', 'CombineLatest'));
    export('Operators/Compact', import('RxW3Operators', 'Compact'));
    export('Operators/Concat', import('RxW3Operators', 'Concat'));
    export('Operators/ConcatMap', import('RxW3Operators', 'ConcatMap'));
    export('Operators/Contains', import('RxW3Operators', 'Contains'));
    export('Operators/Count', import('RxW3Operators', 'Count'));
    export('Operators/Debounce', import('RxW3Operators', 'Debounce'));
    export('Operators/DefaultIfEmpty', import('RxW3Operators', 'DefaultIfEmpty'));
    export('Operators/Delay', import('RxW3Operators', 'Delay'));
    export('Operators/Distinct', import('RxW3Operators', 'Distinct'));
    export('Operators/DistinctUntilChanged', import('RxW3Operators', 'DistinctUntilChanged'));
    export('Operators/ElementAt', import('RxW3Operators', 'ElementAt'));
    export('Operators/Exhaust', import('RxW3Operators', 'Exhaust'));
    export('Operators/ExhaustMap', import('RxW3Operators', 'ExhaustMap'));
    export('Operators/Filter', import('RxW3Operators', 'Filter'));
    export('Operators/Find', import('RxW3Operators', 'Find'));
    export('Operators/First', import('RxW3Operators', 'First'));
    export('Operators/FlatMap', import('RxW3Operators', 'FlatMap'));
    export('Operators/FlatMapLatest', import('RxW3Operators', 'FlatMapLatest'));
    export('Operators/Flatten', import('RxW3Operators', 'Flatten'));
    export('Operators/IgnoreElements', import('RxW3Operators', 'IgnoreElements'));
    export('Operators/Last', import('RxW3Operators', 'Last'));
    export('Operators/Map', import('RxW3Operators', 'Map'));
    export('Operators/Max', import('RxW3Operators', 'Max'));
    export('Operators/Merge', import('RxW3Operators', 'Merge'));
    export('Operators/Min', import('RxW3Operators', 'Min'));
    export('Operators/Pack', import('RxW3Operators', 'Pack'));
    export('Operators/Partition', import('RxW3Operators', 'Partition'));
    export('Operators/Pluck', import('RxW3Operators', 'Pluck'));
    export('Operators/Reduce', import('RxW3Operators', 'Reduce'));
    export('Operators/Reject', import('RxW3Operators', 'Reject'));
    export('Operators/Retry', import('RxW3Operators', 'Retry'));
    export('Operators/Sample', import('RxW3Operators', 'Sample'));
    export('Operators/Scan', import('RxW3Operators', 'Scan'));
    export('Operators/Skip', import('RxW3Operators', 'Skip'));
    export('Operators/SkipLast', import('RxW3Operators', 'SkipLast'));
    export('Operators/SkipUntil', import('RxW3Operators', 'SkipUntil'));
    export('Operators/SkipWhile', import('RxW3Operators', 'SkipWhile'));
    export('Operators/StartWith', import('RxW3Operators', 'StartWith'));
    export('Operators/Sum', import('RxW3Operators', 'Sum'));
    export('Operators/Switch', import('RxW3Operators', 'Switch'));
    export('Operators/SwitchMap', import('RxW3Operators', 'SwitchMap'));
    export('Operators/Take', import('RxW3Operators', 'Take'));
    export('Operators/TakeLast', import('RxW3Operators', 'TakeLast'));
    export('Operators/TakeUntil', import('RxW3Operators', 'TakeUntil'));
    export('Operators/TakeWhile', import('RxW3Operators', 'TakeWhile'));
    export('Operators/Tap', import('RxW3Operators', 'Tap'));
    export('Operators/Unpack', import('RxW3Operators', 'Unpack'));
    export('Operators/Unwrap', import('RxW3Operators', 'Unwrap'));
    export('Operators/Window', import('RxW3Operators', 'Window'));
    export('Operators/With', import('RxW3Operators', 'With'));
    export('Operators/Zip', import('RxW3Operators', 'Zip'));
end)